apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: single-pipelinerun-
spec:
  serviceAccountName: tekton-triggers-example-sa
  pipelineRef:
    name: build-single-image
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  params:
  # You can get description in pipeline.yaml
  - name: image-registry
    value: paddlecloud/paddleocr
  - name: toolkit-repo-name
    value: PaddleOCR
  - name: toolkit-revision
    value: release/2.4
  - name: toolkit-base-image-tag
    value: 2.2.2
  - name: docker-repo-url
    value: https://github.com/freeliuzc/PaddleCloud.git
  - name: docker-revision
    value: dev-tekton
  - name: dockerfile-path
    value: tekton/dockerfiles/Dockerfile



