FROM paddlepaddle/paddle:2.3.0


COPY PaddleNLP ./PaddleNLP
COPY PaddleSlim ./PaddleSlim

RUN pip3.7 install --upgrade pip
RUN pip3.7 install jupyter -U && pip3.7 install jupyterlab

WORKDIR /home/PaddleSlim

RUN pip3.7 install -r requirements.txt
RUN python3.7 setup.py install

WORKDIR /home/PaddleNLP

RUN pip3.7 install visualdl regex pybind11 LAC zstandard
RUN pip3.7 install paddlepaddle=2.3.0
RUN pip3.7 install -r requirements.txt
RUN python3.7 setup.py install

CMD ["sleep", "infinity"]
