apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pfsserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pfsserver
    spec:
      volumes:
      - name: cert-volume
        hostPath:
          path: /home/pcloud_gongwb/data/certs
      - name: data-storage
        cephfs:
          monitors: 
            - 172.19.32.166:6789
          path: "/"
          user: "admin"
          secretRef:
            name: ceph-secret
      containers:
      - name: pfs
        imagePullPolicy: Always
        image: gongweibao/pfsserver:latest
        volumeMounts:
        - name: cert-volume
          mountPath: /certs
        - name: data-storage
          mountPath: /pfs/datacenter1/home/
        ports:
        - containerPort: 8080
        command: ["/pfsserver/pfsserver", "-tokenuri", "http://cloud1.paddlepaddle.org", "-logtostderr=true", "-log_dir=./log", "-v=3"]
      nodeSelector:
        kubernetes.io/hostname: k8s-node1
     
