apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pfsserver
  namespace: paddlecloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pfsserver
    spec:
      volumes:
      - name: public-data-storage
        cephfs:
          # Notice: change ip to your's
          monitors: ["ip:6789"]
          user: "admin"
          path: "/public/dataset"
          secretRef:
            name: ceph-secret
          readOnly: true
      - name: data-storage
        cephfs:
          # Notice: change ip to your's
          monitors: ["ip:6789"]
          user: "admin"
          path: "/"
          secretRef:
            name: ceph-secret
      containers:
      - name: pfs
        imagePullPolicy: Always
        # Notice: change repo to your's
        image: <repo>/paddlepaddle/pfsserver:latest
        env:
          - name: CURRENT_DATACENTER
            value: "datacenter"
        command: ["/pfsserver/pfsserver", "-tokenuri", "http://paddle-cloud-service:8000", "-logtostderr=true", "-log_dir=./log", "-v=4"]
        volumeMounts:
        - name: data-storage
          mountPath: /pfs/datacenter/home
        - name: public-data-storage
          mountPath: /pfs/datacenter/public/dataset
        ports:
        - containerPort: 8080
     
