apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kaniko-cache
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/liuzichang01/pv/cache"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kaniko-cache
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-runtime-1
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/liuzichang01/pv/runtime-1"
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-runtime-2
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/liuzichang01/pv/runtime-2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-runtime-3
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/liuzichang01/pv/runtime-3"
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-runtime-4
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/liuzichang01/pv/runtime-4"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-runtime-5
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/liuzichang01/pv/runtime-5"