apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: multi-pipelinerun-
spec:
  serviceAccountName: tekton-triggers-example-sa
  pipelineRef:
    name: build-multi-image
  workspaces:
# Temporary volume which will be deleted when the pipeline finishes.
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
# Cache space for kaniko
  - name: cache
    persistentVolumeClaim:
      claimName: pvc-kaniko-cache
  timeout: 6h
  params:
  - name: image-registry
    value: paddlecloud/paddleocr
  - name: toolkit-repo-name
    value: PaddleOCR
  - name: toolkit-revision
    value: release/2.4
  - name: toolkit-base-image-version
    value: 2.2.2
  - name: docker-repo-url
    value: https://github.com/freeliuzc/PaddleCloud.git
  - name: docker-revision
    value: dev-tekton
  - name: dockerfile-path
    value: tekton/dockerfiles/Dockerfile


  
    