apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-single-image
spec:
  params:
  - name: toolkit-repo-name
    type: string
    description: The repo name. (PaddleOCR/PaddleDetection/PaddleNLP/PaddleSeg/PaddleClas/PaddleSpeech/PaddleRec)
  - name: toolkit-revision
    type: string
    description: The branch of paddle toolkit to clone.
  - name: toolkit-base-image-tag
    type: string
    description: Tag of the paddle base image. Found in https://hub.docker.com/r/paddlepaddle/paddle/tags.
    default: 2.2.2
  - name: docker-repo-url
    type: string
    description: The git repository containing Dockerfile.
  - name: docker-revision
    type: string
    description: The branch of the docker repo to clone.
  - name: image-registry
    type: string
    description: The image registry to push.
  - name: context-path
    type: string
    description: The directory path containing Dockerfile and dependency files within repo.
  - name: dockerfile-path
    type: string
    description: The relative path to context path.  
  - name: kaniko-image
    type: string
    description: kaniko image to use.
    default: lzc842650834/tekton:kaniko-project-executor-v1.5.1
  workspaces:
  - name: shared-data
    description: Shared storage space for git repo.
  - name: cache
    description: Cache dir for kaniko. It should be a PV.
  tasks:
  - name: fetch-paddle-toolkit-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: https://github.com/PaddlePaddle/$(params.toolkit-repo-name)
    - name: revision
      value: $(params.toolkit-revision)
    - name: subdirectory
      value: $(params.toolkit-repo-name)
    - name: httpProxy
      value: http://172.19.57.45:3128/
    - name: httpsProxy
      value: http://172.19.57.45:3128/
  - name: fetch-docker-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.docker-repo-url)
    - name: revision
      value: $(params.docker-revision)
    - name: subdirectory
      value: repo-docker
    - name: httpProxy
      value: http://172.19.57.45:3128/
    - name: httpsProxy
      value: http://172.19.57.45:3128/
  - name: parse-and-prepare
    taskRef:
      name: prepare-build-env
    runAfter: 
      - fetch-docker-repo
      - fetch-paddle-toolkit-repo
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: toolkit-name
      value: $(params.toolkit-repo-name)
    - name: revision
      value: $(params.toolkit-revision)
    - name: paddle-base-tag
      value: $(params.toolkit-base-image-tag)
    - name: toolkit-dir
      value: $(params.toolkit-repo-name)
    - name: context-path
      value: $(params.context-path)
    - name: dockerfile-path
      value: $(params.dockerfile-path)
  - name: build-image
    runAfter:
      - parse-and-prepare
    taskRef:
      name: kaniko
    params:
      - name: IMAGE
        value: "$(params.image-registry):$(tasks.parse-and-prepare.results.image-tag-branch)-$(tasks.parse-and-prepare.results.image-tag-env)-$(tasks.fetch-paddle-toolkit-repo.results.commit-id)"
      - name: IMAGE_BAIDU
        value: "registry.baidubce.com/paddleflow-public/$(tasks.parse-and-prepare.results.toolkit-name-lower):$(tasks.parse-and-prepare.results.image-tag-branch)-$(tasks.parse-and-prepare.results.image-tag-env)-$(tasks.fetch-paddle-toolkit-repo.results.commit-id)"
      - name: CONTEXT
        value: docker
      - name: DOCKERFILE
        value: $(params.dockerfile-path)
      - name: BUILDER_IMAGE
        value: $(params.kaniko-image)
      - name: EXTRA_ARGS
        value: 
          - --build-arg=IMAGE_TAG=$(params.toolkit-base-image-tag)
          - --build-arg=PADDLE_TOOLKIT=$(params.toolkit-repo-name)
    workspaces:
      - name: source
        workspace: shared-data
      - name: cache
        workspace: cache

