apiVersion: v1
kind: Pod
metadata:
  name: kaniko-warmer
spec:
  containers:
  - name: kaniko-warmer
    image: gcr.io/kaniko-project/warmer:latest
    args: ["--cache-dir=/cache",
           "--image=paddlepaddle/paddle:2.3.0",
           "--image=paddlepaddle/paddle:2.3.0-gpu-cuda10.2-cudnn7",
           "--image=paddlepaddle/paddle:2.3.0-gpu-cuda11.2-cudnn8",]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
      - name: kaniko-cache
        mountPath: /cache
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-push
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: pvc-kaniko-cache
