ARG IMAGE_TAG=2.2.2
ARG PADDLE_VERSION=2.2.2
FROM paddlepaddle/paddle:${IMAGE_TAG}

ARG PADDLE_VERSION
RUN pip3.7 install --upgrade pip  \
    pip3.7 install paddlepaddle-gpu==${PADDLE_VERSION}

COPY PaddleDetection ./PaddleDetection

WORKDIR /home/PaddleDetection

RUN pip3.7 install -r requirements.txt && \
    pip3.7 install jupyter

CMD ["sleep", "infinity"]
