apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: rawjob-pserver
spec:
  replicas: 4
  template:
    metadata:
      labels:
        paddle-job-pserver: fluid_raw_job
    spec:
      hostNetwork: true
      imagePullSecrets:
      - name: job-registry-secret
      containers:
      - name: pserver
        image: "yourimage"
        imagePullPolicy: Always
        ports:
        - name: jobport-30487
          containerPort: 30487
        env:
        - name: PADDLE_JOB_NAME
          value: rawjob
        - name: TRAINERS
          value: "4"
        - name: PSERVERS
          value: "4"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/nvidia/lib64"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        command: ["python", "trainer.py"]
        resources:
          requests:
            memory: 8Gi
            cpu: 1
          limits:
            memory: 12Gi
            cpu: 1
      
