FROM registry.baidubce.com/paddlepaddle/paddle:2.2.2-jupyter

WORKDIR /home

RUN apt-get update && apt-get install unzip && \
    pip install --upgrade pip -i https://mirror.baidu.com/pypi/simple && \
    pip install paddlepaddle==2.2.2 -i https://mirror.baidu.com/pypi/simple && \
    wget https://github.com/PaddlePaddle/PaddleDetection/archive/refs/heads/release/2.4.zip && \
    unzip 2.4.zip && mv PaddleDetection-release-2.4 PaddleDetection && rm -rf 2.4.zip

WORKDIR /home/PaddleDetection

RUN pip install -r requirements.txt -i https://mirror.baidu.com/pypi/simple && \
    wget https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip && \
    wget https://bj.bcebos.com/v1/paddledet/models/pipeline/strongbaseline_r50_30e_pa100k.zip && \
    wget https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip && \
    wget https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip && \
    unzip -d output_inference mot_ppyoloe_l_36e_pipeline.zip && \
    unzip -d output_inference strongbaseline_r50_30e_pa100k.zip && \
    unzip -d output_inference dark_hrnet_w32_256x192.zip && \
    unzip -d output_inference STGCN.zip

CMD ["sleep", "infinity"]

# docker build . -t registry.baidubce.com/paddleflow-public/paddledetection:2.4-jupyter
