apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cron-listener
  annotations:
    tekton.dev/payload-validation: "false"
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
  - name: cron-trig
    bindings:
    - ref: cron-binding
    template:
      ref: cron-template

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cron-template
spec:
  params:
  - name: image-dockerhub-registry
  - name: image-baidubce-registry
  - name: toolkit-repo-name
  - name: toolkit-revision
  - name: toolkit-base-image-version
  - name: docker-repo-url
  - name: docker-revision
  - name: context-path
  - name: dockerfile-path
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: multi-pipelinerun-
    spec:
      serviceAccountName: tekton-triggers-example-sa
      pipelineRef:
        name: build-multi-image
      podTemplate:
        hostNetwork: true
      workspaces:
      # Temporary volume which will be deleted when the pipeline finishes.
        - name: shared-data
          volumeClaimTemplate:
            spec:
              storageClassName: manual
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 15Gi
      # Cache space for kaniko
        - name: cache
          persistentVolumeClaim:
            claimName: pvc-kaniko-cache
      timeout: 7h
      params:
      - name: image-dockerhub-registry
        value: $(tt.params.image-dockerhub-registry)
      - name: image-baidubce-registry
        value: $(tt.params.image-baidubce-registry)
      - name: toolkit-repo-name
        value: $(tt.params.toolkit-repo-name)
      - name: toolkit-revision      # (branch, tag, sha, ref, etc...)
        value: $(tt.params.toolkit-revision)
      - name: toolkit-base-image-version
        value: $(tt.params.toolkit-base-image-version)
      - name: docker-repo-url
        value: $(tt.params.docker-repo-url)
      - name: docker-revision      # (branch, tag, sha, ref, etc...)
        value: $(tt.params.docker-revision)
      - name: context-path
        value: $(tt.params.context-path)
      - name: dockerfile-path
        value: $(tt.params.dockerfile-path)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cron-binding
spec:
  params:
  - name: image-dockerhub-registry
    value: $(body.image-dockerhub-registry)
  - name: image-baidubce-registry
    value: $(body.image-baidubce-registry)
  - name: toolkit-repo-name
    value: $(body.toolkit-repo-name)
  - name: toolkit-revision
    value: $(body.toolkit-revision)
  - name: toolkit-base-image-version
    value: $(body.toolkit-base-image-version)
  - name: docker-repo-url
    value: $(body.docker-repo-url)
  - name: docker-revision
    value: $(body.docker-revision)
  - name: context-path
    value: $(body.context-path)
  - name: dockerfile-path
    value: $(body.dockerfile-path)

